
INSERT INTO public.reviews (product_id, product_handle, customer_name, rating, title, content, is_approved, is_verified_purchase, helpful_count) VALUES
-- Black Pure Silk Batik Print Saree
('gid://shopify/Product/9127269204186', 'black-pure-silk-batik-print-saree-with-bird-motifs-korasutra', 'Priya Sharma', 5, 'Absolutely stunning batik work', 'The bird motifs on this saree are breathtaking. The batik print has such fine detailing that you can see the artisan craftsmanship in every inch. The silk quality is premium and the drape is beautiful. Wore it to a family wedding and received so many compliments!', true, true, 3),
('gid://shopify/Product/9127269204186', 'black-pure-silk-batik-print-saree-with-bird-motifs-korasutra', 'Rekha Venkatesh', 5, 'Museum quality piece', 'This is not just a saree, it is wearable art. The black silk catches the light beautifully and the bird motifs are so intricate. I have a collection of handloom sarees and this one stands out. The packaging was also very premium.', true, true, 5),
('gid://shopify/Product/9127269204186', 'black-pure-silk-batik-print-saree-with-bird-motifs-korasutra', 'Anita Joshi', 4, 'Beautiful but runs slightly long', 'The batik work is gorgeous and the silk quality is top notch. I found the length slightly more than expected but that is actually a good thing for taller women. The colour is rich and deep. Very happy with my purchase.', true, true, 1),

-- Black Tissue Tussar Jamdani Saree
('gid://shopify/Product/9127269531866', 'black-tissue-tussar-jamdani-saree-with-lotus-needlework-korasutra', 'Kavitha Reddy', 5, 'Exceptional Jamdani craftsmanship', 'The lotus needlework on this Tussar saree is exquisite. You can tell this was woven by master artisans. The tissue texture gives it a beautiful sheen without being too flashy. Perfect for evening events and festive occasions.', true, true, 4),
('gid://shopify/Product/9127269531866', 'black-tissue-tussar-jamdani-saree-with-lotus-needlework-korasutra', 'Sunita Menon', 4, 'Lovely saree, worth the price', 'The Jamdani work is very fine and detailed. The lotus motifs are beautifully done. The Tussar silk has a lovely natural texture. I wore this for Diwali celebrations and it looked absolutely regal. Delivery was prompt too.', true, true, 2),

-- Brown Tussar Silk Baluchari Saree
('gid://shopify/Product/9127269630170', 'brown-tussar-silk-baluchari-saree-with-handwoven-motifs-korasutra', 'Deepa Iyer', 5, 'A true heirloom piece', 'This Baluchari saree is a masterpiece. The handwoven motifs tell stories from our mythology and the brown Tussar silk has such a rich, warm tone. I am keeping this as a family heirloom. The quality is outstanding.', true, true, 6),
('gid://shopify/Product/9127269630170', 'brown-tussar-silk-baluchari-saree-with-handwoven-motifs-korasutra', 'Lakshmi Narayanan', 5, 'Incredible weaving detail', 'Every inch of this saree shows the dedication of the weaver. The Baluchari motifs are intricate and the Tussar silk drapes beautifully. I have received more compliments wearing this than any designer saree I own.', true, true, 3),
('gid://shopify/Product/9127269630170', 'brown-tussar-silk-baluchari-saree-with-handwoven-motifs-korasutra', 'Meera Chatterjee', 4, 'Beautiful traditional piece', 'The Baluchari work is authentic and the silk quality is premium. The brown colour is earthy and elegant. Slight colour variation from photos but in a good way - looks even richer in person. Highly recommend for special occasions.', true, true, 2),

-- Green Blended Silk Kantha Stitch Saree
('gid://shopify/Product/9127269794010', 'green-blended-silk-kantha-stitch-saree-with-swan-motif-korasutra', 'Sneha Kulkarni', 5, 'Stunning swan motifs', 'The Kantha stitch work on this saree is phenomenal. The swan motifs are so graceful and the green silk is a gorgeous shade. I wore this to my cousin engagement and everyone wanted to know where I got it from!', true, true, 4),
('gid://shopify/Product/9127269794010', 'green-blended-silk-kantha-stitch-saree-with-swan-motif-korasutra', 'Rina Das', 4, 'Lovely handwork', 'The Kantha stitch is clearly hand done - you can feel the texture and see the artisan touch. The green colour is fresh and vibrant. Very comfortable to wear all day. Good value for the craftsmanship.', true, true, 1),

-- Maroon Pure Silk Kantha Stitch Saree
('gid://shopify/Product/9127269892314', 'maroon-pure-silk-kantha-stitch-saree-with-lotus-motif-threadwork-korasutra', 'Padmini Nair', 5, 'Royal and elegant', 'The maroon silk is so rich and the Kantha lotus motifs are absolutely divine. This saree makes you feel like royalty. The threadwork is fine and delicate. I wore it for my daughter wedding and it was the talk of the evening.', true, true, 7),
('gid://shopify/Product/9127269892314', 'maroon-pure-silk-kantha-stitch-saree-with-lotus-motif-threadwork-korasutra', 'Anjali Saxena', 5, 'Worth every rupee', 'I was hesitant about the price but after receiving this saree I understand why. The pure silk quality is exceptional and the Kantha stitch lotus motifs are a work of art. The maroon colour is deep and sophisticated.', true, true, 3),
('gid://shopify/Product/9127269892314', 'maroon-pure-silk-kantha-stitch-saree-with-lotus-motif-threadwork-korasutra', 'Sujata Bhatt', 4, 'Beautiful craftsmanship', 'Lovely Kantha work on premium silk. The lotus threadwork is intricate and beautiful. The maroon shade is exactly as shown in photos. Very happy with the purchase. Would love to see more colour options.', true, true, 2),

-- Pink Linen Jamdani Saree
('gid://shopify/Product/9127269925082', 'pink-linen-jamdani-saree-with-needlework-korasutra', 'Divya Krishnamurthy', 5, 'Perfect for office and evenings', 'This pink linen Jamdani is so versatile! The needlework is delicate and the linen fabric breathes so well in hot weather. I have worn it to office and for dinner outings. Gets better with every wash.', true, true, 4),
('gid://shopify/Product/9127269925082', 'pink-linen-jamdani-saree-with-needlework-korasutra', 'Radhika Gupta', 4, 'Lovely linen saree', 'Beautiful Jamdani work on soft linen. The pink shade is subtle and elegant. Very comfortable for daily wear. The needlework adds just the right amount of detail without being over the top. Great buy!', true, true, 2),

-- Blue Muslin Silk Saree
('gid://shopify/Product/9142948430042', 'blue-muslin-silk-saree-with-zari-sequins-border-korasutra', 'Pooja Agarwal', 5, 'Dreamy muslin silk', 'The muslin silk blend is so soft and the blue colour is ethereal. The zari sequins border adds just the right amount of sparkle. Perfect for festive occasions. The drape is effortless and elegant.', true, true, 5),
('gid://shopify/Product/9142948430042', 'blue-muslin-silk-saree-with-zari-sequins-border-korasutra', 'Nandini Rao', 4, 'Beautiful festive saree', 'Love the zari border on this muslin silk. The blue is a beautiful shade and the sequins catch light beautifully. Comfortable to wear for long events. Would recommend for weddings and festivals.', true, true, 2),

-- Grey Hand Paint Tussar Saree
('gid://shopify/Product/9137711743194', 'grey-hand-paint-tussar-saree-with-floral-motif-korasutra', 'Sudha Murthy', 5, 'Unique hand painted beauty', 'Each floral motif on this Tussar saree is hand painted and you can see the artistic touch. The grey base is sophisticated and the floral work adds warmth. A unique piece that stands out in any gathering.', true, true, 3),
('gid://shopify/Product/9137711743194', 'grey-hand-paint-tussar-saree-with-floral-motif-korasutra', 'Kamala Krishnan', 4, 'Art on fabric', 'The hand painting is exquisite. Every flower is slightly different which makes it truly unique. The Tussar silk has a lovely natural texture. A conversation starter at every event I have worn it to.', true, true, 2),

-- Blue Handloom Tussar Saree
('gid://shopify/Product/9133899022554', 'blue-handloom-tussar-saree-with-flower-motifs-korasutra', 'Vaishnavi Deshpande', 5, 'Gorgeous handloom quality', 'The handloom quality of this Tussar saree is evident from the first touch. The blue colour is serene and the flower motifs are woven beautifully. Feels like wearing heritage. Absolutely love it!', true, true, 4),
('gid://shopify/Product/9133899022554', 'blue-handloom-tussar-saree-with-flower-motifs-korasutra', 'Tara Shankar', 4, 'Authentic handloom', 'Beautiful handloom Tussar with lovely flower motifs. The blue shade is calming and elegant. You can feel the authenticity in the weave. Excellent customer service from Kora Sutra.', true, true, 1),

-- Blue Tussar Silk Baluchari Saree
('gid://shopify/Product/9133899743450', 'blue-tussar-silk-baluchari-saree-with-handwoven-motifs-korasutra', 'Indira Varma', 5, 'Magnificent Baluchari', 'The blue Tussar Baluchari is absolutely magnificent. The handwoven motifs are detailed and the silk quality is premium. This is the kind of saree that becomes a family heirloom. Thrilled with my purchase.', true, true, 5),
('gid://shopify/Product/9133899743450', 'blue-tussar-silk-baluchari-saree-with-handwoven-motifs-korasutra', 'Sarita Bose', 5, 'A collector piece', 'As a handloom collector, this Baluchari exceeds expectations. The weaving technique is traditional and the blue Tussar silk is luminous. Worth every penny for anyone who appreciates authentic Indian textiles.', true, true, 3),

-- Black and Yellow Silk Block Print Saree
('gid://shopify/Product/9137803460826', 'black-and-yellow-silk-block-print-saree-with-leaf-motifs-korasutra', 'Geeta Ramachandran', 5, 'Bold and beautiful', 'The black and yellow combination is striking and the block print leaf motifs are crisp and clear. The silk quality is excellent. This saree makes a statement. Perfect for events where you want to stand out.', true, true, 3),
('gid://shopify/Product/9137803460826', 'black-and-yellow-silk-block-print-saree-with-leaf-motifs-korasutra', 'Shobha Pillai', 4, 'Eye catching block print', 'Love the contrast of black and yellow. The block print is clearly hand done with slight variations that give it character. The silk drapes beautifully. A unique addition to my saree collection.', true, true, 2),

-- Cream Pure Silk Kantha Stitch
('gid://shopify/Product/9162120790234', 'cream-pure-silk-kantha-stitch-with-warli-threadwork-korasutra', 'Aruna Devi', 5, 'Warli art on silk - incredible', 'The Warli threadwork on cream silk is such a unique concept. It looks like a tribal painting come to life on fabric. The Kantha stitch adds beautiful texture. I wore this for an art gallery opening and it was perfect.', true, true, 4),
('gid://shopify/Product/9162120790234', 'cream-pure-silk-kantha-stitch-with-warli-threadwork-korasutra', 'Malini Hegde', 4, 'Unique and artistic', 'Never seen Warli art on a saree before. The cream silk is elegant and the threadwork is detailed. Very unique piece that bridges traditional art forms. Great conversation starter at any gathering.', true, true, 2),

-- Bottle Green Linen Handloom Jamdani
('gid://shopify/Product/9142564389082', 'bottle-green-linen-handloom-jamdani-saree-lotus-motif-needlework-with-zari-pallu-korasutra', 'Jayashree Mohan', 5, 'Elegant green with golden zari', 'The bottle green linen with zari pallu is an absolute showstopper. The Jamdani lotus motifs are woven with such precision. The linen is comfortable even in summer heat. The zari pallu adds festive elegance.', true, true, 5),
('gid://shopify/Product/9142564389082', 'bottle-green-linen-handloom-jamdani-saree-lotus-motif-needlework-with-zari-pallu-korasutra', 'Parvathi Krishnan', 4, 'Beautiful linen Jamdani', 'Love the combination of handloom linen with Jamdani weaving. The lotus needlework is beautiful and the zari pallu is the perfect finishing touch. Comfortable and elegant for office wear.', true, true, 2);
